### ISSUE TITLE
Citation information would be helpful

### ISSUE THREAD

**Issue by MichaelRoeder** [PoDiGG/podigg#10]
It would be really nice, if the README file would contain the information how the work can be cited (i.e., which paper should be cited if the generator is used for a publication).

**Comment by rubensworks** [comment]
Thanks for the suggestion! I've added a link to the article in the README.

For reference, here's the bibtex:

```
@article{taelman_swj_podigg_2018,
  author = {Taelman, Ruben and Colpaert, Pieter and Mannens, Erik and Verborgh, Ruben},
  title = {Generating Public Transport Data based on Population Distributions for RDF Benchmarking},
  journal = {Semantic Web Journal},
  year = {2018},
  month = jul,
  url = {http://rubensworks.net/raw/publications/2018/podigg.pdf}
}
```
